server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    platform: org.hibernate.dialect.Oracle10gDialect
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: info